#!/usr/bin/env node

import fetch from 'node-fetch';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

// Load environment variables
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '..', '.env') });

// Configuration
const CONFIG = {
  serverUrl: process.env.SERVER_URL || 'http://localhost:3000',
  token: process.env.MCP_HTTP_TOKEN || 'dev-token'
};

// Helper to make authenticated requests
async function apiCall(endpoint, body) {
  const response = await fetch(`${CONFIG.serverUrl}${endpoint}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${CONFIG.token}`
    },
    body: JSON.stringify(body)
  });
  
  if (!response.ok) {
    const error = await response.json().catch(() => ({ error: response.statusText }));
    throw new Error(`API Error (${response.status}): ${error.error || 'Unknown error'}`);
  }
  
  return response.json();
}

// Main CLI function
async function runBrief(topic) {
  console.log(`\n🔍 Researching: "${topic}"\n`);
  
  // Step 1: Search the web
  console.log('Step 1/4: Searching the web...');
  const searchResults = await apiCall('/tools/search_web', {
    query: topic,
    k: 5
  });
  
  if (!searchResults || searchResults.length === 0) {
    console.error('❌ No search results found');
    process.exit(1);
  }
  
  console.log(`   Found ${searchResults.length} results`);
  
  // Step 2: Fetch readable content from top 3 domains
  console.log('Step 2/4: Fetching content from top sources...');
  const docs = [];
  const seenDomains = new Set();
  
  for (const result of searchResults) {
    const domain = new URL(result.url).hostname;
    if (seenDomains.has(domain)) continue;
    if (docs.length >= 3) break;
    
    try {
      const readable = await apiCall('/tools/fetch_readable', { url: result.url });
      if (readable.text && readable.text.length > 100) {
        docs.push(readable);
        seenDomains.add(domain);
        console.log(`   ✓ Fetched: ${readable.title.slice(0, 50)}...`);
      }
    } catch (err) {
      console.log(`   ✗ Failed to fetch: ${result.url.slice(0, 50)}...`);
    }
  }
  
  if (docs.length === 0) {
    console.error('❌ Could not fetch readable content from any source');
    process.exit(1);
  }
  
  // Step 3: Summarize with citations
  console.log('Step 3/4: Summarizing with LLM...');
  const summary = await apiCall('/tools/summarize_with_citations', {
    topic,
    docs
  });
  
  // Step 4: Generate and save markdown
  console.log('Step 4/4: Saving markdown...');
  
  const date = new Date().toISOString().split('T')[0];
  const filename = `brief_${date}`;
  
  const markdown = generateMarkdown(topic, summary, date);
  
  const saved = await apiCall('/tools/save_markdown', {
    filename,
    content: markdown
  });
  
  console.log(`\n✅ Brief saved to: ${saved.path}\n`);
  console.log('─'.repeat(60));
  console.log(markdown);
  console.log('─'.repeat(60));
  
  return saved.path;
}

// Generate markdown content
function generateMarkdown(topic, summary, date) {
  const lines = [
    `# Research Brief: ${topic}`,
    '',
    `**Date:** ${date}`,
    '',
    '## Key Findings',
    ''
  ];
  
  for (const bullet of summary.bullets) {
    lines.push(`- ${bullet}`);
  }
  
  lines.push('');
  lines.push('## Sources');
  lines.push('');
  
  for (const source of summary.sources) {
    lines.push(`${source.i}. [${source.title}](${source.url})`);
  }
  
  lines.push('');
  lines.push('---');
  lines.push(`*Generated by Research Briefing Server*`);
  
  return lines.join('\n');
}

// Parse CLI arguments
function parseArgs() {
  const args = process.argv.slice(2);
  
  if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
    console.log(`
Research Briefing CLI

Usage:
  brief "<your topic>"
  npm run brief -- "<your topic>"

Examples:
  brief "artificial intelligence trends 2024"
  brief "climate change solutions"
  brief "quantum computing advances"

Environment Variables:
  SERVER_URL       Server URL (default: http://localhost:3000)
  MCP_HTTP_TOKEN   Bearer token for authentication

The CLI will:
  1. Search the web for your topic
  2. Fetch readable content from top 3 sources
  3. Summarize findings using a local LLM
  4. Save the brief as markdown
`);
    process.exit(0);
  }
  
  return args.join(' ');
}

// Main entry point
const topic = parseArgs();

runBrief(topic).catch(err => {
  console.error(`\n❌ Error: ${err.message}\n`);
  
  if (err.message.includes('ECONNREFUSED')) {
    console.error('Make sure the server is running: npm start');
  }
  
  process.exit(1);
});
